// Quant Salary Explorer - Seed Data & Region/City Config
// Region -> Country -> Cities mapping
const REGION_DATA = {
  "US": { countries: { "United States": ["New York", "Chicago", "San Francisco", "Boston", "Greenwich", "Austin", "Miami"] }},
  "UK": { countries: { "United Kingdom": ["London", "Edinburgh", "Cambridge", "Oxford", "Manchester"] }},
  "EU": { countries: { "France": ["Paris", "Lyon"], "Germany": ["Frankfurt", "Munich", "Berlin"], "Netherlands": ["Amsterdam", "Rotterdam"], "Switzerland": ["Zurich", "Geneva"], "Ireland": ["Dublin"], "Luxembourg": ["Luxembourg City"] }},
  "APAC": { countries: { "Singapore": ["Singapore"], "Hong Kong": ["Hong Kong"], "Japan": ["Tokyo"], "Australia": ["Sydney", "Melbourne"], "China": ["Shanghai", "Beijing", "Shenzhen"], "India": ["Mumbai", "Bangalore", "Hyderabad", "Pune", "Gurgaon", "Chennai"] }},
  "EMEA": { countries: { "UAE": ["Dubai", "Abu Dhabi"], "Saudi Arabia": ["Riyadh"], "South Africa": ["Johannesburg", "Cape Town"], "Israel": ["Tel Aviv"], "Qatar": ["Doha"] }}
};

const ROLES = ["Quant Developer","Quant Researcher","Quant Trader","Risk Quant","Model Validation","Algo Trader","Data Scientist - Quant"];
const LEVELS = ["Intern","Junior / Analyst","Mid / Associate","Senior / VP","Lead / Director","Principal / MD"];
const EDUCATION = ["PhD","Masters","Bachelors","Self-Taught"];
const CURRENCIES = { "US":"USD","UK":"GBP","EU":"EUR","APAC":"USD","EMEA":"USD" };

// Real-world representative seed salaries from global hubs
const SEED_DATA = [
  // --- US Region (5 Entries) ---
  {
    id: "seed-us-1",
    region: "US",
    country: "United States",
    city: "New York",
    firm: "Jane Street",
    role: "Quant Trader",
    level: "Junior / Analyst",
    yoe: 1,
    base: 300000,
    bonus: 200000,
    equity: 0,
    total_comp: 500000,
    currency: "USD",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-us-2",
    region: "US",
    country: "United States",
    city: "New York",
    firm: "Citadel",
    role: "Quant Researcher",
    level: "Mid / Associate",
    yoe: 3,
    base: 250000,
    bonus: 250000,
    equity: 0,
    total_comp: 500000,
    currency: "USD",
    education: "PhD",
    is_seed: true
  },
  {
    id: "seed-us-3",
    region: "US",
    country: "United States",
    city: "New York",
    firm: "Two Sigma",
    role: "Quant Developer",
    level: "Senior / VP",
    yoe: 6,
    base: 280000,
    bonus: 320000,
    equity: 50000,
    total_comp: 650000,
    currency: "USD",
    education: "Masters",
    is_seed: true
  },
  {
    id: "seed-us-4",
    region: "US",
    country: "United States",
    city: "Chicago",
    firm: "Jump Trading",
    role: "Algo Trader",
    level: "Mid / Associate",
    yoe: 4,
    base: 225000,
    bonus: 275000,
    equity: 0,
    total_comp: 500000,
    currency: "USD",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-us-5",
    region: "US",
    country: "United States",
    city: "New York",
    firm: "Point72",
    role: "Risk Quant",
    level: "Junior / Analyst",
    yoe: 2,
    base: 180000,
    bonus: 120000,
    equity: 0,
    total_comp: 300000,
    currency: "USD",
    education: "Masters",
    is_seed: true
  },

  // --- UK Region (5 Entries) ---
  {
    id: "seed-uk-1",
    region: "UK",
    country: "United Kingdom",
    city: "London",
    firm: "G-Research",
    role: "Quant Researcher",
    level: "Mid / Associate",
    yoe: 3,
    base: 160000,
    bonus: 140000,
    equity: 0,
    total_comp: 300000,
    currency: "GBP",
    education: "PhD",
    is_seed: true
  },
  {
    id: "seed-uk-2",
    region: "UK",
    country: "United Kingdom",
    city: "London",
    firm: "Man Group",
    role: "Quant Developer",
    level: "Senior / VP",
    yoe: 7,
    base: 175000,
    bonus: 165000,
    equity: 20000,
    total_comp: 360000,
    currency: "GBP",
    education: "Masters",
    is_seed: true
  },
  {
    id: "seed-uk-3",
    region: "UK",
    country: "United Kingdom",
    city: "London",
    firm: "Marshall Wace",
    role: "Quant Trader",
    level: "Junior / Analyst",
    yoe: 2,
    base: 130000,
    bonus: 110000,
    equity: 0,
    total_comp: 240000,
    currency: "GBP",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-uk-4",
    region: "UK",
    country: "United Kingdom",
    city: "London",
    firm: "Barclays Capital",
    role: "Model Validation",
    level: "Mid / Associate",
    yoe: 4,
    base: 115000,
    bonus: 55000,
    equity: 0,
    total_comp: 170000,
    currency: "GBP",
    education: "Masters",
    is_seed: true
  },
  {
    id: "seed-uk-5",
    region: "UK",
    country: "United Kingdom",
    city: "London",
    firm: "Citadel Securities",
    role: "Algo Trader",
    level: "Junior / Analyst",
    yoe: 1,
    base: 145000,
    bonus: 125000,
    equity: 0,
    total_comp: 270000,
    currency: "GBP",
    education: "Bachelors",
    is_seed: true
  },

  // --- EU Region (5 Entries) ---
  {
    id: "seed-eu-1",
    region: "EU",
    country: "Netherlands",
    city: "Amsterdam",
    firm: "Optiver",
    role: "Quant Trader",
    level: "Junior / Analyst",
    yoe: 2,
    base: 150000,
    bonus: 150000,
    equity: 0,
    total_comp: 300000,
    currency: "EUR",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-eu-2",
    region: "EU",
    country: "Netherlands",
    city: "Amsterdam",
    firm: "Flow Traders",
    role: "Quant Developer",
    level: "Mid / Associate",
    yoe: 4,
    base: 110000,
    bonus: 130000,
    equity: 10000,
    total_comp: 250000,
    currency: "EUR",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-eu-3",
    region: "EU",
    country: "France",
    city: "Paris",
    firm: "Squarepoint Capital",
    role: "Quant Researcher",
    level: "Senior / VP",
    yoe: 6,
    base: 160000,
    bonus: 170000,
    equity: 20000,
    total_comp: 350000,
    currency: "EUR",
    education: "PhD",
    is_seed: true
  },
  {
    id: "seed-eu-4",
    region: "EU",
    country: "Germany",
    city: "Frankfurt",
    firm: "Deutsche Bank",
    role: "Risk Quant",
    level: "Mid / Associate",
    yoe: 3,
    base: 105000,
    bonus: 35000,
    equity: 0,
    total_comp: 140000,
    currency: "EUR",
    education: "Masters",
    is_seed: true
  },
  {
    id: "seed-eu-5",
    region: "EU",
    country: "Switzerland",
    city: "Zurich",
    firm: "AllianceBernstein",
    role: "Model Validation",
    level: "Lead / Director",
    yoe: 8,
    base: 210000,
    bonus: 160000,
    equity: 0,
    total_comp: 370000,
    currency: "CHF",
    education: "PhD",
    is_seed: true
  },

  // --- APAC Region (5 Entries) ---
  {
    id: "seed-apac-1",
    region: "APAC",
    country: "Singapore",
    city: "Singapore",
    firm: "DRW",
    role: "Quant Trader",
    level: "Mid / Associate",
    yoe: 3,
    base: 200000,
    bonus: 160000,
    equity: 0,
    total_comp: 360000,
    currency: "USD",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-apac-2",
    region: "APAC",
    country: "Singapore",
    city: "Singapore",
    firm: "Flow Traders",
    role: "Quant Developer",
    level: "Junior / Analyst",
    yoe: 2,
    base: 140000,
    bonus: 100000,
    equity: 0,
    total_comp: 240000,
    currency: "USD",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-apac-3",
    region: "APAC",
    country: "Hong Kong",
    city: "Hong Kong",
    firm: "Millennium",
    role: "Quant Researcher",
    level: "Senior / VP",
    yoe: 5,
    base: 1600000,
    bonus: 1400000,
    equity: 0,
    total_comp: 3000000,
    currency: "HKD",
    education: "PhD",
    is_seed: true
  },
  {
    id: "seed-apac-4",
    region: "APAC",
    country: "Australia",
    city: "Sydney",
    firm: "Macquarie Group",
    role: "Risk Quant",
    level: "Mid / Associate",
    yoe: 4,
    base: 190000,
    bonus: 120000,
    equity: 0,
    total_comp: 310000,
    currency: "AUD",
    education: "Masters",
    is_seed: true
  },
  {
    id: "seed-apac-5",
    region: "APAC",
    country: "India",
    city: "Mumbai",
    firm: "Nomura",
    role: "Model Validation",
    level: "Junior / Analyst",
    yoe: 2,
    base: 3200000,
    bonus: 1200000,
    equity: 0,
    total_comp: 4400000,
    currency: "INR",
    education: "Masters",
    is_seed: true
  },

  // --- EMEA Region (5 Entries) ---
  {
    id: "seed-emea-1",
    region: "EMEA",
    country: "UAE",
    city: "Abu Dhabi",
    firm: "Abu Dhabi Investment Authority (ADIA)",
    role: "Quant Researcher",
    level: "Senior / VP",
    yoe: 7,
    base: 250000,
    bonus: 220000,
    equity: 0,
    total_comp: 470000,
    currency: "USD",
    education: "PhD",
    is_seed: true
  },
  {
    id: "seed-emea-2",
    region: "EMEA",
    country: "UAE",
    city: "Dubai",
    firm: "Hedge Fund",
    role: "Quant Trader",
    level: "Mid / Associate",
    yoe: 3,
    base: 180000,
    bonus: 150000,
    equity: 0,
    total_comp: 330000,
    currency: "USD",
    education: "Bachelors",
    is_seed: true
  },
  {
    id: "seed-emea-3",
    region: "EMEA",
    country: "Saudi Arabia",
    city: "Riyadh",
    firm: "Risk Advisory",
    role: "Risk Quant",
    level: "Mid / Associate",
    yoe: 4,
    base: 150000,
    bonus: 80000,
    equity: 0,
    total_comp: 230000,
    currency: "USD",
    education: "Masters",
    is_seed: true
  },
  {
    id: "seed-emea-4",
    region: "EMEA",
    country: "Israel",
    city: "Tel Aviv",
    firm: "WorldQuant",
    role: "Quant Researcher",
    level: "Junior / Analyst",
    yoe: 2,
    base: 460000,
    bonus: 300000,
    equity: 0,
    total_comp: 760000,
    currency: "ILS",
    education: "PhD",
    is_seed: true
  },
  {
    id: "seed-emea-5",
    region: "EMEA",
    country: "Israel",
    city: "Tel Aviv",
    firm: "Hedge Fund",
    role: "Quant Developer",
    level: "Senior / VP",
    yoe: 6,
    base: 680000,
    bonus: 520000,
    equity: 50000,
    total_comp: 1250000,
    currency: "ILS",
    education: "Masters",
    is_seed: true
  }
];
