-- Run this in your Supabase SQL Editor to create the availability table

create table availability_patterns (
  id bigint generated by default as identity primary key,
  day_of_week text not null, -- 'Monday', 'Tuesday', etc.
  start_time time not null,  -- '10:00'
  end_time time not null,    -- '18:00'
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(day_of_week)
);

-- Insert default rows (Mon-Sat, 10 AM to 6 PM IST)
insert into availability_patterns (day_of_week, start_time, end_time, is_active) values
('Monday', '10:00', '18:00', true),
('Tuesday', '10:00', '18:00', true),
('Wednesday', '10:00', '18:00', true),
('Thursday', '10:00', '18:00', true),
('Friday', '10:00', '18:00', true),
('Saturday', '10:00', '14:00', true),
('Sunday', '00:00', '00:00', false);

-- Enable Row Level Security (RLS)
alter table availability_patterns enable row level security;

-- Allow read access to everyone
create policy "Public Availability Read"
on availability_patterns for select
using (true);

-- Allow write/update (For simplicity in this setup, ideally restrict to Admin)
create policy "Public Availability Write"
on availability_patterns for insert
with check (true);

create policy "Public Availability Update"
on availability_patterns for update
using (true);
